################################################################################
#
#  Copyright (C) 2001-2023 Force Dimension, Switzerland.
#  All Rights Reserved.
#
#  Force Dimension SDK 3.17.6
#
################################################################################

# GLFW dependency
LDLIBS += -lglfw
